---
title: "Hola Mundo"
author: "Geomorfología (GEO-131)"
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
output:
  bookdown::github_document2:
    number_sections: false
    fig_caption: yes
  # bookdown::html_document2:
  #   number_sections: false
  #   code_folding: hide
  #   fig_caption: yes
  #   md_extensions: "-fancy_lists"
  #   css: estilos.css
  #   toc: true
  #   toc_depth: 3
editor_options: 
  chunk_output_type: console
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, out.width = '100%', fig.retina = 4)
```

```{r, include=F}
output_format <- knitr::opts_knit$get("rmarkdown.pandoc.to")
repo_url <- system("git config --get remote.origin.url", intern = TRUE)
repo_name <- sub(".git$", "", basename(repo_url))
org_name <- basename(dirname(repo_url))
rmd_filename <- tools::file_path_sans_ext(basename(knitr::current_input()))
github_pages_url <- paste0("https://", org_name, ".github.io/", repo_name, "/", rmd_filename, ".html")
```

```{r, results='asis', echo=F}
if (grepl('gfm', output_format)) {
  cat('Versión HTML (quizá más legible), [aquí](', github_pages_url, ')\n', sep = '')
} else if (output_format == 'latex') {
  cat('Versión HTML (quizá más legible), [aquí](', github_pages_url, ')\n', sep = '')
}
```

> "Sin embargo, el mundo nunca responde"


